default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: postgres
  pool: 5

development:
  <<: *default
  database: cleco_store_development

production:
  <<: *default
  database: cleco_store_prod
